import asyncio
import json
import re
import os
import pathlib
import sys
from datetime import datetime, date
from typing import Any, Dict, List, Optional
from datetime import datetime, date, time, timedelta

import streamlit as st
from dotenv import load_dotenv
from groq import Groq

# Ensure the repo root is on sys.path so we can import server.py from the frontend folder.
ROOT_DIR = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT_DIR))

import server

load_dotenv()

MODEL_NAME = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")


def init_session_state() -> None:
    if "messages" not in st.session_state:
        st.session_state.messages = [
            {
                "role": "system",
                "content": (
                    "You are an HRMS AI Assistant. When a user asks to perform an HR action:\n"
                    "- Always call the appropriate tool.\n"
                    "- Never invent missing values.\n"
                    "- If required tool parameters are missing, call the tool with the available parameters only.\n\n"
                    "The application will detect missing parameters and ask the user for them.\n\n"
                    "Examples:\n\n"
                    "User: Add employee John\n\n"
                    "Tool:\n"
                    "add_employee(\n"
                    'emp_name="John"\n'
                    ")\n\n"
                    "User: Add employee Sarah Johnson with manager E001 and email sarah.johnson@atliq.com\n\n"
                    "Tool:\n"
                    "add_employee(\n"
                    'emp_name="Sarah Johnson"\n'
                    'manager_id="E001"\n'
                    'email="sarah.johnson@atliq.com"\n'
                    ")\n\n"
                    "Employee IDs are auto-generated by the system; do not ask the user to provide emp_id.\n\n"
                    "User: Get leave balance\n\n"
                    "Tool:\n"
                    "get_employee_leave_balance()\n\n"
                    "If required information is missing for a tool call:\n\n"
                    "DO NOT invent values.\n"
                    "DO NOT guess employee IDs.\n"
                    "DO NOT guess dates.\n"
                    "Call the tool with only the information explicitly provided by the user.\n"
                    "The application will collect any missing fields.\n"
                )
                + " Use the available tools to fulfill user requests for employee onboarding, ticket creation, meeting scheduling, leave applications, and HR email workflows. Reply with a short summary of the result. Only use tools when required and avoid inventing data.",
            }
        ]


def get_tool_definitions() -> List[Dict[str, Any]]:
    if "tool_definitions" in st.session_state:
        return st.session_state.tool_definitions

    tool_definitions: List[Dict[str, Any]] = []
    tools = asyncio.run(server.mcp.list_tools())
    for tool in tools:
        if tool.inputSchema is None:
            continue
        tool_definitions.append(
            {
                "name": tool.name,
                "description": (tool.description or "").strip(),
                "parameters": tool.inputSchema,
            }
        )

    st.session_state.tool_definitions = tool_definitions
    return tool_definitions


def format_for_display(value: Any) -> str:
    try:
        if (
            isinstance(value, tuple)
            and len(value) == 2
            and isinstance(value[1], dict)
            and "result" in value[1]
        ):
            return format_for_display(value[1]["result"])

        if isinstance(value, dict):

            field_names = {
                "emp_id": "Employee ID",
                "name": "Name",
                "manager_id": "Manager ID",
                "email": "Email",
                "hired_date": "Hired Date",
                "balance": "Leave Balance",
                "status": "Status",
                "ticket_id": "Ticket ID",
                "meeting_code": "Meeting Code",
            }

            lines = []

            for key, val in value.items():
                display_name = field_names.get(key, key.replace("_", " ").title())

                lines.append(f"• **{display_name}**: {val}")

            return "\n\n".join(lines)
        if isinstance(value, list):
            if all(isinstance(item, dict) for item in value):
                keys = sorted({key for item in value for key in item.keys()})
                header = "| " + " | ".join(keys) + " |"
                separator = "| " + " | ".join("---" for _ in keys) + " |"
                rows = [
                    "| " + " | ".join(str(item.get(key, "")) for key in keys) + " |"
                    for item in value
                ]
                return "\n".join([header, separator] + rows)

            cleaned = []
            for item in value:
                cleaned.append(format_for_display(item))
            return "\n\n".join(cleaned)

        if isinstance(value, str):
            trimmed = value.strip()
            # If it's a JSON string, parse and format it
            if trimmed.startswith("{") and trimmed.endswith("}"):
                try:
                    parsed = json.loads(trimmed)
                    return format_for_display(parsed)
                except Exception:
                    pass

            if "text='" in value:
                try:
                    start = value.index("text='") + 6
                    end = value.index("'", start)
                    return value[start:end]
                except Exception:
                    pass
        return str(value)
    except Exception:
        return str(value)


def get_tool_required_fields(name: str) -> List[str]:
    defs = get_tool_definitions()
    for t in defs:
        if t.get("name") == name:
            params = t.get("parameters") or {}
            return params.get("required", [])
    return []


PLACEHOLDER_WORDS = [
    "employee id",
    "manager id",
    "leave dates",
    "date",
    "email",
    "list of leave dates",
    "unknown",
    "n/a",
]

MANUAL_REQUIRED_FIELDS = {
    "apply_leave": ["emp_id", "leave_dates"],
    "add_employee": ["emp_name", "manager_id", "email"],
    "update_employee_details": ["emp_id"],
    "create_ticket": ["emp_id", "item", "reason"],
    "schedule_meeting": ["employee_ids", "start_datetime", "duration_minutes", "topic"],
    "cancel_meeting": ["meeting_code"],
    "get_employee_leave_balance": ["emp_id"],
}


def validate_tool_args(tool_name: str, args: Dict[str, Any]):
    required = MANUAL_REQUIRED_FIELDS.get(
        tool_name,
        get_tool_required_fields(tool_name),
    )

    missing = []
    for field in required:
        value = args.get(field)
        if value is None:
            missing.append(field)
            continue
        if isinstance(value, str):
            if value.strip() == "":
                missing.append(field)
                continue
            if value.lower().strip() in PLACEHOLDER_WORDS:
                missing.append(field)
                continue
        if isinstance(value, list):
            if len(value) == 0:
                missing.append(field)
                continue
            if "leave date" in str(value).lower():
                missing.append(field)
    return missing


def parse_tool_call(choice: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    message = choice.get("message", {}) or {}
    tool_calls = message.get("tool_calls") or []
    if tool_calls:
        function = tool_calls[0].get("function", {})
        try:
            return {
                "name": function["name"],
                "arguments": json.loads(function["arguments"]),
            }
        except Exception:
            return None

    function_call = message.get("function_call")
    if function_call:
        try:
            return {
                "name": function_call["name"],
                "arguments": json.loads(function_call["arguments"]),
            }
        except Exception:
            return None
    return None


def call_human_readable_tool(name: str, arguments: Dict[str, Any]):
    try:
        result = asyncio.run(server.mcp.call_tool(name, arguments))
        print(type(result))
        print(result)
        return True, format_for_display(result)

    except ValueError as exc:
        return False, str(exc)

    except Exception:
        return False, (
            "Something went wrong while processing your request. " "Please try again."
        )


def call_groq(messages: List[Dict[str, str]]) -> Dict[str, Any]:
    if not GROQ_API_KEY:
        raise RuntimeError(
            "Missing GROQ_API_KEY. Set it in your environment or in a .env file."
        )

    client = Groq(api_key=GROQ_API_KEY)
    completion = client.chat.completions.create(
        messages=messages,
        model=MODEL_NAME,
        functions=get_tool_definitions(),
        function_call="auto",
        temperature=0.0,
        max_tokens=500,
    )
    return completion.model_dump()


def run_assistant(user_text: str) -> str:
    messages = [
        {"role": item["role"], "content": item["content"]}
        for item in st.session_state.messages
    ]

    response = call_groq(messages)
    choice = response["choices"][0]
    tool_call = parse_tool_call(choice)
    assistant_content = choice["message"].get("content") or ""
    # If the model is making a tool call, don't show the raw function call content to the user.
    assistant_text = "" if tool_call else assistant_content

    if tool_call:
        tool_name = tool_call.get("name")
        tool_args = tool_call.get("arguments") or {}

        missing = validate_tool_args(tool_name, tool_args)

        if missing:
            st.session_state.pending_tool_call = {
                "name": tool_name,
                "arguments": tool_args,
                "missing": missing,
            }
            assistant_text = (
                f"I need additional details to run `{tool_name}`:\n\n"
                + "\n".join(f"• {field}" for field in missing)
            )
        else:
            success, result = call_human_readable_tool(tool_name, tool_args)
            if success:
                assistant_text = f"✅ {result}"
            else:
                assistant_text = f"❌ {result}"

    if not assistant_text:
        assistant_text = (
            "✅ Received response from the model, but no assistant text was returned."
        )

    st.session_state.messages.append({"role": "assistant", "content": assistant_text})
    return assistant_text


def render_chat() -> None:
    st.set_page_config(
        page_title="HRMS AI Assistant",
        layout="centered",
        initial_sidebar_state="expanded",
    )
    st.markdown(
        """
    <style>
    section[data-testid="stSidebar"] button {
        height: 55px;
        font-size: 18px !important;
        margin-bottom: 8px;
    }
    </style>
    """,
        unsafe_allow_html=True,
    )

    if "page" not in st.session_state:
        st.session_state.page = "Chat"

    st.sidebar.title("🏢 HRMS Assist")

    if st.sidebar.button("💬 Chat Assistant", use_container_width=True):
        st.session_state.page = "Chat"

    if st.sidebar.button("👤 Employees", use_container_width=True):
        st.session_state.page = "Employees"

    if st.sidebar.button("🎫 Tickets", use_container_width=True):
        st.session_state.page = "Tickets"

    if st.sidebar.button("🏖 Leaves", use_container_width=True):
        st.session_state.page = "Leaves"

    if st.sidebar.button("📅 Meetings", use_container_width=True):
        st.session_state.page = "Meetings"

    page = st.session_state.page
    if page == "Chat":
        st.title("💬 HR Assistant")

        st.write(
            "Ask HR-related questions in natural language. The assistant can retrieve employee information, leave details, tickets, meetings, and perform HR operations through integrated tools."
        )
        chat_container = st.container()

        with chat_container:

            for message in st.session_state.messages:

                if message["role"] == "system":
                    continue

                with st.chat_message(message["role"]):
                    st.markdown(message["content"])

        pending = st.session_state.get(
            "pending_tool_call"
        )  # st.session_state.get("pending_tool_call") is used to check if there is a pending tool call that requires additional information from the user. If the assistant has identified that it needs more details to execute a tool (e.g., missing parameters), it stores this information in st.session_state under the key "pending_tool_call". This allows the app to persist this state across user interactions and display a form to collect the missing information when the user returns to the chat interface.
        if pending:
            st.markdown(f"**Provide details for `{pending['name']}`**")
            with st.form(key="pending_tool_form"):
                new_vals: Dict[str, Any] = {}
                for field in pending["missing"]:
                    default = pending["arguments"].get(field, "")
                    new_vals[field] = st.text_input(field, value=str(default))
                submit = st.form_submit_button("Submit details")
            if submit:
                combined_args = {**pending["arguments"], **new_vals}
                with st.spinner("Running tool..."):
                    success, result = call_human_readable_tool(
                        pending["name"], combined_args
                    )
                if success:
                    message_text = f"✅ {result}"
                else:
                    message_text = f"⚠️ {result}"
                st.session_state.messages.append(
                    {"role": "assistant", "content": message_text}
                )
                st.session_state.pending_tool_call = None
                st.rerun()

        if GROQ_API_KEY is None:
            st.warning(
                "Set `GROQ_API_KEY` in your environment or in a local `.env` file, then refresh this app."
            )

        user_input = st.chat_input("Ask HR Assistant")

        if user_input:

            st.session_state.messages.append({"role": "user", "content": user_input})

            try:

                with st.spinner("Thinking..."):
                    run_assistant(user_input)

            except Exception as exc:

                error_msg = str(exc)

                st.session_state.messages.append(
                    {"role": "assistant", "content": f"Error: {error_msg}"}
                )

            st.rerun()

    elif page == "Employees":
        st.title("👤 Employee Management")

        st.write(
            "Manage employee records, onboard new employees, update employee information, and maintain organizational reporting structures."
        )

        st.header("Employees")
        if "employee_toast" in st.session_state:
            st.toast(st.session_state["employee_toast"], icon="✅")
            del st.session_state["employee_toast"]
        employee_list = server.employee_manager.list_employees()
        employee_ids = [row["emp_id"] for row in employee_list]

        employee_filter = st.selectbox(
            "Filter by employee", ["All"] + employee_ids, key="employee_filter"
        )
        if employee_filter == "All":
            filtered_employees = employee_list
        else:
            filtered_employees = [
                row for row in employee_list if row["emp_id"] == employee_filter
            ]

        st.dataframe(filtered_employees)

        with st.expander("Add a new employee"):
            with st.form("add_employee_form"):
                new_name = st.text_input("Employee name", key="new_employee_name")
                new_manager_id = st.selectbox(
                    "Manager ID", [""] + employee_ids, key="new_employee_manager_id"
                )
                new_email = st.text_input("Email", key="new_employee_email")

                add_submit = st.form_submit_button(
                    "Add employee", key="add_employee_submit"
                )

            if add_submit:
                if not (
                    new_name.strip() and new_manager_id.strip() and new_email.strip()
                ):
                    st.error("Please fill all fields.")

                elif "@" not in new_email or "." not in new_email:
                    st.error("Please enter a valid email.")

                else:
                    try:
                        generated_id = server.employee_manager.get_next_emp_id()

                        server.employee_manager.add_employee(
                            server.EmployeeCreate(
                                emp_id=generated_id,
                                name=new_name.strip(),
                                manager_id=new_manager_id.strip(),
                                email=new_email.strip(),
                            )
                        )

                        st.session_state["employee_toast"] = (
                            f"Employee {generated_id} added successfully."
                        )
                        st.rerun()

                    except Exception as exc:
                        st.error(str(exc))

        with st.expander("Update employee Details"):
            with st.form("update_employee_form"):
                update_emp_id = st.selectbox(
                    "Employee ID", [""] + employee_ids, key="update_emp_id"
                )

                updated_name = st.text_input("Updated name", key="update_emp_name")

                updated_manager_id = st.selectbox(
                    "Updated manager ID",
                    ["", "None"] + employee_ids,
                    key="update_manager_id",
                )

                updated_email = st.text_input("Updated email", key="update_emp_email")

                update_submit = st.form_submit_button(
                    "Update employee", key="update_employee_submit"
                )

            if update_submit:

                update_fields_present = bool(
                    updated_name.strip()
                    or updated_manager_id.strip()
                    or updated_email.strip()
                )

                if not update_emp_id.strip():
                    st.error("Please select an employee.")
                elif not update_fields_present:
                    st.error("Please provide at least one field to update.")
                else:
                    try:
                        manager_value = (
                            None
                            if updated_manager_id in ["", "None"]
                            else updated_manager_id
                        )

                        server.employee_manager.update_employee(
                            emp_id=update_emp_id,
                            name=updated_name.strip() or None,
                            manager_id=manager_value,
                            email=updated_email.strip() or None,
                        )

                        st.session_state["employee_toast"] = (
                            f"Employee {update_emp_id} updated successfully."
                        )
                        st.rerun()

                    except Exception as exc:
                        st.error(str(exc))

    elif page == "Tickets":
        st.title("🎫 Ticket Management")

        st.write(
            "Create, track, and update employee support requests. Monitor ticket statuses and manage issue resolution workflows."
        )

        st.header("Tickets")
        if "ticket_toast" in st.session_state:
            st.toast(st.session_state["ticket_toast"], icon="✅")
            del st.session_state["ticket_toast"]
        ticket_employee_ids = [
            row["emp_id"] for row in server.employee_manager.list_employees()
        ]
        selected_emp = st.selectbox(
            "Filter by employee", ["All"] + ticket_employee_ids, key="ticket_filter_emp"
        )
        status_options = ["All", "Open", "In Progress", "Closed", "Rejected"]
        selected_status = st.selectbox(
            "Filter by status", status_options, key="ticket_filter_status"
        )

        tickets = server.ticket_manager.list_tickets(
            employee_id=None if selected_emp == "All" else selected_emp,
            status=None if selected_status == "All" else selected_status,
        )
        st.dataframe(tickets)

        with st.expander("Create a new ticket"):
            with st.form("create_ticket_form"):
                ticket_emp_id = st.selectbox(
                    "Employee ID", [""] + ticket_employee_ids, key="ticket_emp_id"
                )
                ticket_item = st.text_input("Issue type", key="ticket_item")
                ticket_reason = st.text_area("Reason", key="ticket_reason")
                create_submit = st.form_submit_button(
                    "Create ticket", key="create_ticket_submit"
                )
            if create_submit:
                if not str(ticket_emp_id).strip():
                    st.error("Please select an Employee ID.")

                elif not str(ticket_item).strip():
                    st.error("Please enter an Issue Type.")

                elif not str(ticket_reason).strip():
                    st.error("Please enter a Reason.")

                else:
                    try:
                        message = server.ticket_manager.create_ticket(
                            server.TicketCreate(
                                emp_id=ticket_emp_id,
                                item=ticket_item.strip(),
                                reason=ticket_reason.strip(),
                            )
                        )

                        st.session_state["ticket_toast"] = message
                        st.rerun()

                    except Exception as exc:
                        st.error(str(exc))

        with st.expander("Update ticket status"):
            current_tickets = server.ticket_manager.list_tickets()
            ticket_ids = [row["ticket_id"] for row in current_tickets]
            with st.form("update_ticket_form"):
                update_ticket_id = st.selectbox(
                    "Ticket ID", [""] + ticket_ids, key="update_ticket_id"
                )
                update_status = st.selectbox(
                    "Status",
                    ["", "Open", "In Progress", "Closed", "Rejected"],
                    key="update_ticket_status",
                )
                update_ticket_submit = st.form_submit_button(
                    "Update status", key="update_ticket_submit"
                )

            if update_ticket_submit:
                if not str(update_ticket_id).strip():
                    st.error("Please select a Ticket ID.")

                elif not str(update_status).strip():
                    st.error("Please select a Status.")

                else:
                    try:
                        message = server.ticket_manager.update_ticket_status(
                            server.TicketStatusUpdate(status=update_status),
                            update_ticket_id,
                        )

                        st.session_state["ticket_toast"] = message

                        st.rerun()

                    except Exception as exc:
                        st.error(str(exc))

    elif page == "Leaves":
        st.title("🏖 Leave Management")

        st.write(
            "View employee leave balances, review leave history, and submit leave requests while ensuring balance and policy compliance."
        )
        st.header("Leaves")
        if "leave_toast" in st.session_state:
            st.toast(st.session_state["leave_toast"], icon="🏖️")
            del st.session_state["leave_toast"]
        balances = server.leave_manager.list_balances()
        st.dataframe(balances)

        leave_employee_ids = [row["emp_id"] for row in balances]
        selected_leave_emp = st.selectbox(
            "Select employee for leave history",
            ["None"] + leave_employee_ids,
            key="leave_history_emp",
        )
        if selected_leave_emp != "None":
            if hasattr(server.leave_manager, "get_leave_history_records"):
                history_dates = server.leave_manager.get_leave_history_records(
                    selected_leave_emp
                )
            else:
                history_text = server.leave_manager.get_leave_history(
                    selected_leave_emp
                )
                # If the fallback returns a summary string, parse dates out for display
                history_dates = []
                if ": " in history_text:
                    date_str = history_text.split(": ", 1)[1].strip().rstrip(".")
                    history_dates = [
                        d.strip() for d in date_str.split(",") if d.strip()
                    ]

            st.markdown(
                f"**Leave history for {selected_leave_emp} — {len(history_dates)} day(s)**"
            )
            if history_dates:
                for leave_date in history_dates:
                    st.markdown(f"- {leave_date}")
            else:
                st.info("No leave history found for this employee.")

        with st.expander("Apply for leave"):
            with st.form("apply_leave_form"):
                apply_emp_id = st.selectbox(
                    "Employee ID", [""] + leave_employee_ids, key="apply_leave_emp_id"
                )
                leave_dates = st.date_input(
                    "Select leave period",
                    value=(),
                    min_value=date.today(),
                    key="leave_dates",
                )
                apply_submit = st.form_submit_button(
                    "Apply leave", key="apply_leave_submit"
                )

            if apply_submit:

                if not apply_emp_id:
                    st.error("Please select an Employee ID.")

                elif len(leave_dates) != 2:
                    st.error("Please select a start date and end date.")

                else:
                    try:
                        start_date, end_date = leave_dates

                        parsed_dates = []
                        current = start_date

                        while current <= end_date:
                            parsed_dates.append(current)
                            current += timedelta(days=1)

                        req = server.LeaveApplyRequest(
                            emp_id=apply_emp_id, leave_dates=parsed_dates
                        )

                        message = server.leave_manager.apply_leave(req)

                        st.session_state["leave_toast"] = message
                        st.rerun()

                    except Exception as exc:
                        st.error(str(exc))

    elif page == "Meetings":
        st.title("📅 Meeting Scheduler")

        st.write(
            "Schedule meetings, manage participants, track meeting statuses, and cancel upcoming meetings when required."
        )
        if "meeting_toast" in st.session_state:
            st.toast(st.session_state["meeting_toast"], icon="✅")
            del st.session_state["meeting_toast"]
        meetings = server.meeting_manager.list_all_meetings()
        st.dataframe(meetings)

        meeting_employee_ids = [
            row["emp_id"] for row in server.employee_manager.list_employees()
        ]
        with st.expander("Schedule meeting"):
            with st.form("schedule_meeting_form"):

                meeting_emp_ids = st.multiselect(
                    "Employee IDs",
                    meeting_employee_ids,
                    key="meeting_emp_ids",
                )

                meeting_date = st.date_input(
                    "Meeting Date",
                    min_value=date.today(),
                    key="meeting_date",
                )

                time_slots = []

                selected_date = meeting_date
                today = date.today()

                if selected_date == today:

                    now = datetime.now()

                    next_minute = ((now.minute // 15) + 1) * 15

                    if next_minute == 60:
                        start_hour = now.hour + 1
                        start_minute = 0
                    else:
                        start_hour = now.hour
                        start_minute = next_minute

                else:
                    start_hour = 9
                    start_minute = 0

                current_time = time(start_hour, start_minute)

                end_time = time(18, 0)

                while current_time <= end_time:

                    time_slots.append(current_time.strftime("%I:%M %p"))

                    current_datetime = datetime.combine(selected_date, current_time)

                    next_datetime = current_datetime + timedelta(minutes=15)

                    current_time = next_datetime.time()

                meeting_time = st.selectbox(
                    "Meeting Time",
                    time_slots,
                    key="meeting_time",
                )

                meeting_duration = st.number_input(
                    "Duration (minutes)",
                    min_value=15,
                    max_value=480,
                    value=60,
                    step=15,
                    key="meeting_duration",
                )

                meeting_topic = st.text_input(
                    "Topic",
                    key="meeting_topic",
                )

                schedule_submit = st.form_submit_button(
                    "Schedule meeting",
                    key="schedule_meeting_submit",
                )

            if schedule_submit:

                if not meeting_emp_ids:
                    st.error("Please select at least one employee.")

                elif not str(meeting_topic).strip():
                    st.error("Please enter a meeting topic.")

                else:
                    try:

                        selected_time = datetime.strptime(
                            meeting_time, "%I:%M %p"
                        ).time()

                        meeting_dt = datetime.combine(meeting_date, selected_time)

                        if meeting_dt < datetime.now():
                            st.error("Meeting start time cannot be in the past.")

                        else:

                            message = server.meeting_manager.schedule_meeting(
                                server.MeetingCreate(
                                    emp_ids=meeting_emp_ids,
                                    start_dt=meeting_dt,
                                    duration_minutes=meeting_duration,
                                    topic=meeting_topic.strip(),
                                )
                            )

                        st.session_state["meeting_toast"] = message
                        st.rerun()

                    except Exception as exc:
                        st.error(str(exc))
        with st.expander("Cancel meeting"):
            meetings_list = server.meeting_manager.list_all_meetings()
            meeting_codes = [
                row["meeting_code"]
                for row in meetings_list
                if row["status"] != "Cancelled"
            ]
            if not meeting_codes:
                st.info("No active meetings available to cancel.")
            with st.form("cancel_meeting_form"):
                cancel_meeting_code = st.selectbox(
                    "Meeting Code",
                    [""] + meeting_codes,
                    key="cancel_meeting_code",
                )
                cancel_submit = st.form_submit_button(
                    "Cancel meeting",
                    key="cancel_meeting_submit",
                )

            if cancel_submit:
                if not str(cancel_meeting_code).strip():
                    st.error("Please select a meeting.")
                else:
                    try:
                        message = server.meeting_manager.cancel_meeting_by_id(
                            cancel_meeting_code
                        )

                        st.session_state["meeting_toast"] = message
                        st.rerun()
                    except Exception as exc:
                        st.error(str(exc))


if __name__ == "__main__":
    init_session_state()
    get_tool_definitions()
    render_chat()
